[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "21c75d7e38296d895f2135eb3dc7c956c8ce9d48"
os = "macos"

    [[SPEX.download]]
    sha256 = "08df517304c44b0adb93905bbe08cb9e4f6f464923c13c8ded459c597090d88f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.aarch64-apple-darwin.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "50cdd31a1e2c2b8744bf4259edd2c89ca9025453"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "f85eff90249cf9e252cca840830ad5f329e842187dad6a750d11a74bd77a3c86"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.aarch64-linux-gnu.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "0fd4a4ca7a66400b45676e2be8b93003d907e020"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "deb97ca1d6ade7e7ffa3bef4756a8924eb98145c4263ee184d4bbe67af8eb96f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.aarch64-linux-musl.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "eab5a52d9908377266c27cdebd8bd0365821187c"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "03ae398ee7897c21bbed41ac4e39638fd096a4372db026ed9fdb44a04275ef19"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.aarch64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1dcaaf0d15d2314ad8a19122de7e844ac9835283"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "73b5575e7ccd6bb300e192d19efd7ed716a08dcb23ce0f144876958e0ee92c95"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.armv6l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "299b77f5e43a5eee186fbfaa75e5075089d89ec7"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "8364030a80657fd1e294e6493cbd04828d1617e695c934ae02b1fbe136a10479"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.armv6l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0462c42dc94802e8062b28fdf80244df64329243"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "32ef7505dee551cb6774cb8f690288646a8931931f76a7bd180d8be568ad171c"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.armv7l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce57bfe56b634e34d0b494c18f65c4427012cee3"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "14ce327aa63ef0d9f5b5bb2dad563318c91b10e8000d99e315e061ad5be3b3d0"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.armv7l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "af3983ab4dd2db187fd635e604872c0cbad0de8d"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "2a10c4866eb83cd3d5c0687542d91de8480e3aa784a670554e819a766096e06a"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.i686-linux-gnu.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "1a456eb81049fb2708b66ecbbbd8db369e9e4a00"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "6c55924f3a9d7e3391b8d8a3d97961fceb622aa4297686fbee267aebad6e52ae"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.i686-linux-musl.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "9a54151606f446c4c79339f1d25deb2a7d5c8cfb"
os = "windows"

    [[SPEX.download]]
    sha256 = "8075114de57eaea35e21f9a181212313f7f1ce0f55ed6785e0c657e0626bee08"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.i686-w64-mingw32.tar.gz"
[[SPEX]]
arch = "powerpc64le"
git-tree-sha1 = "319e27715fdc5dc858923d9864aee374b55e4e5b"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "f66ef2ed4e0930ed37ff79ee2af1d36905b6e01d51844af01845ae3f0bf1a909"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.powerpc64le-linux-gnu.tar.gz"
[[SPEX]]
arch = "riscv64"
git-tree-sha1 = "3a9b931531ad902c49006e8fb6464e724751bc65"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "37aa106a21302aa8f7a1ac3b3524523f7d179c3289f6fe0d7da364276653a7fe"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.riscv64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "6378bdbcc443876f66b96f845365c7381a059244"
os = "macos"

    [[SPEX.download]]
    sha256 = "919610c0bd7b2e2401a5185def15bccc215d5d4e056d5f4707c05a4f5dc804ec"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.x86_64-apple-darwin.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "2e212758879ae821b6579aa9648bf26265af14bd"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "a2af3415a2d74d0cf0174351d3e7b2fa5df03bc9281951d7b2516ba5a21f930a"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.x86_64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "fbdc40fffdd1b5dee25fdeebbc638e2bed3e1904"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "809f729c3702e29d866584df9351f8d2ff3c732c103ea3755e70b969af8db6a6"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.x86_64-linux-musl.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "b4c50f47d977cbde2a8a08161853545ba9f01f2e"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "07dc8d7a625e27f7f246a1405b4e4dcc45b608d9fcef108f3599143cc25afa5f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.x86_64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "af2a9a19fb702b77f665aa8cd5069114640d6861"
os = "windows"

    [[SPEX.download]]
    sha256 = "948a87afb42e25d22b4700fae040b235a1c1fcb5cd3e1cc8c887c64ab9929dd7"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+1/SPEX.v3.2.1.x86_64-w64-mingw32.tar.gz"
