[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "bd2aa59a11c8871871723065a08dc4d55a06cf1f"
os = "macos"

    [[SPEX.download]]
    sha256 = "6ff4cc5ddc9e469b541aa7fcc4df1baa893e102add49ef2eef2f0b485cda6507"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.aarch64-apple-darwin.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "eae31d82976c7b46106ab42b0a34aeecf4162d8a"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "61dd8a50461642e471250d6d53d312acc4bfd1e7dc5de78cbf2b5063f8602b3a"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.aarch64-linux-gnu.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "a3a0f8a435183e51ba47471ad398420564aeb7ce"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "44defd9f0f26a9b3039a3be1e6b1ad42c7873045ec6d0bc15b196c3c49f940fd"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.aarch64-linux-musl.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "5aafa98828d8b762826ec70f923c72d6b186b942"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "8885c10de432c2e802a81973101c88adad4ad702e44e90b1a9b6c122de8e17c7"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.aarch64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f1685ce78e6a91ad751b395732912513aee87dbd"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "2c96529b23fe5f3c50d09338060a1ae700ade12ed2cffddc0ef1290f21e72015"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.armv6l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e604fb944692d993514f845ad2f6b711715996b3"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "7de13ff72ef6f38eafc4e1e26dbacefc31003ee189b501c40e6d9dfa5e11128f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.armv6l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a559c95452dded727d2468ffa4b20eca05983c1"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "87ba54ff2b35c49a8b22dd474d6d6d397364297555d2c9ce38f0e326227bde04"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.armv7l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2486b3c8c5d774a5a1950871112d1876b66873ad"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "d73ee2d5e7aabb36da6782d108021590414ee51f17dfe0db5f454711d5ecd8da"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.armv7l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "3ce43c494e78f8f147aacebf6426a5511e8266ad"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "ce070dd621688cdfecdf68c771ae320b2cafcf01909548f706da3004947f337b"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.i686-linux-gnu.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "93bc0b6d334dc163f6074c5466ead23cf7e72ae6"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "cb1ddf242f7c2000be054732c3496051f241991f8102028b7b340c8a4ff47f91"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.i686-linux-musl.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "a3c9288027bd964e6ddbcf746d30ff6ee5879c3e"
os = "windows"

    [[SPEX.download]]
    sha256 = "0aa8729ea01726d97d33fa0dd0c6a2eb42cf8db36e573b6920dfd9d1d378c53f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.i686-w64-mingw32.tar.gz"
[[SPEX]]
arch = "powerpc64le"
git-tree-sha1 = "1655b8a2c37c5b4b61d583190970f8e4b0556887"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "7c1bf1e9f80164beaff359ff6816baab44d1f6cdb81669b98bf8d5750564a715"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.powerpc64le-linux-gnu.tar.gz"
[[SPEX]]
arch = "riscv64"
git-tree-sha1 = "ba5e7ad932ee4e2927885eb76c191fddc043b00a"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "7d70fc71f3b91e1fa451fd203a715d66f36c6a11236967a4f9ec2e49913d0b9d"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.riscv64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "1a6a8f5c3b5f1ed4f0775c1a880e91692b499298"
os = "macos"

    [[SPEX.download]]
    sha256 = "362dab437ac0fb76fc0e8049aa46afe7b0da595fe7806b06d1d8b5259f3f3242"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.x86_64-apple-darwin.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "3e81e438fba5fd36d22dcb601f6e26ee5061e99c"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "d4fa460386e9314c31e9bf52cdb226417ce243f20609df988839ed2c5477d4ac"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.x86_64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "d59d0c188c44c10b7381a860f5d1e19e078ef500"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "c0991efb55d47f0b0aed6bd93482fff2e2efaf698b585ce4bd84c9ce9b235a5e"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.x86_64-linux-musl.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "70af34daebf5408b7785d0e545f54e544ceef169"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "93c0dd04b1b086514fbcf7d4b8e4a3285a776fa8aa91b2d5ea8833702667a7cf"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.x86_64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "93f597493685408d2df0c84cdb2926f1c4e6bf34"
os = "windows"

    [[SPEX.download]]
    sha256 = "9d7db5ef4ed0c9e60454bef3013bd3b4334028a3f0bfb66483deb0bbed85da6b"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.1+0/SPEX.v3.2.1.x86_64-w64-mingw32.tar.gz"
