[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "8376586e4fc73bae9ebe27c9e457b36c48908925"
os = "macos"

    [[SPEX.download]]
    sha256 = "fff02c59d7c71cf48c9390b6056630a850b958e764329e9ad0eb05bfc15c4df2"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.aarch64-apple-darwin.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "eddc2e5e694dcb8926f37d0b8a96c6a04b755bc5"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "5bef02f08e5541e7a087ac02e76b9c2b16fc2b2724baf21212142759e4e5f9e6"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.aarch64-linux-gnu.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "e1e0540cebdd7cafcccc64704818a8c824a8a183"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "4e7d1abd6f0087e9f88cf13d304dc91a8af326ab574ecba98feeb4c7fbf5b5ff"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.aarch64-linux-musl.tar.gz"
[[SPEX]]
arch = "aarch64"
git-tree-sha1 = "0bd4b911bde7e0cd3122fafbc79f3feb728111c3"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "be5a91fc4de7db92522a93a76c8ed50e31b3457660ba61a08c53500242da2539"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.aarch64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8e30002045fd25203a0939a18b132e1c01067d7"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "ea3b60c56252e16aba9ebe19dc853b78cab16f64fc894a19ffcfd4c4317cae16"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.armv6l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed96bd8238769b68999f1c729fe9d361e5cb7f92"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "4d533e056b20617ab80806109e9dd4c902796121a718eca3e77c77ad8c10b000"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.armv6l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32b340e04de7f21be75c71015cc8a376fe6b5a1c"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "65b2be3bde88def14603230960bb32e89cbad8a9176cf24fce5b0f301e855536"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.armv7l-linux-gnueabihf.tar.gz"
[[SPEX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adc5cae9c373981262d728a516415a75a0e037b2"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "8163982e99b5f1146dcf8ae66cfe81c08c185207fbbbb8db1cfec0da7b24b55f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.armv7l-linux-musleabihf.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "b649f7d50acd41cd84632d926217bb596b814950"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "d1da603182c378df03985095b492d16bc83e1d69ef854e47149fc6bf6966307c"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.i686-linux-gnu.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "a7da903bbe8b88ee0e356789b231328012a63825"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "59b56f4aa8effa447b543e0c0f73c6dab5e3c43e1cf0f4b7b879c29485949e8f"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.i686-linux-musl.tar.gz"
[[SPEX]]
arch = "i686"
git-tree-sha1 = "c457e45299ed02afd729e8618604aee80710dfe6"
os = "windows"

    [[SPEX.download]]
    sha256 = "0a0c2caead17d157e9d241f9cbc5e03addd9dbccf68e8cdc9529ed0d24d3c562"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.i686-w64-mingw32.tar.gz"
[[SPEX]]
arch = "powerpc64le"
git-tree-sha1 = "49696eab6c40e1c9920b9300e27a14cf4a6991b2"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "1e1bcb53f562e04d512736e2949846e9c2cfc5c4d2dfd4a4450494311f093841"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.powerpc64le-linux-gnu.tar.gz"
[[SPEX]]
arch = "riscv64"
git-tree-sha1 = "0e852349c19f04f4f0eaaa3bbcb297ba82244d39"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "7134cd9c684b334b969612ebfa1cbd8410cf2f4567cb7c7964f5f8d969831d86"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.riscv64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "a994eee411e41d1cd1de20d8da7a0649e2962e73"
os = "macos"

    [[SPEX.download]]
    sha256 = "dad4e2988ee99195c4a7fe45196af28b247f683ae091d86538371b0a4fe0a0e4"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.x86_64-apple-darwin.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "f78e270405c862447e8ba1e8a88783435d75933b"
libc = "glibc"
os = "linux"

    [[SPEX.download]]
    sha256 = "fd54722656743a27290598c1962609958d87dfb0a2c23b5c5c5338fed41c1954"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.x86_64-linux-gnu.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "f9ca4b7ff0ed7c61d38ec3cddeb92cd908248651"
libc = "musl"
os = "linux"

    [[SPEX.download]]
    sha256 = "285fc9ec8d877128a948bd2470b8d215f30d2b2fb78302f9dc7a39f88d187f6b"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.x86_64-linux-musl.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "806cc5a1b6f66e736446a2c9edb12db98e955d77"
os = "freebsd"

    [[SPEX.download]]
    sha256 = "29e95dd78020c90b031cb798f5899905ec5ee2ee7449ceb6b060c02bcbf3952c"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.x86_64-unknown-freebsd.tar.gz"
[[SPEX]]
arch = "x86_64"
git-tree-sha1 = "4e540ccb4bcc887b329f0ab25c73b01e22635b89"
os = "windows"

    [[SPEX.download]]
    sha256 = "33ec6e98027247394071e4ec32027f607959c43fa558f75b16079e3d3a1ba1d4"
    url = "https://github.com/JuliaBinaryWrappers/SPEX_jll.jl/releases/download/SPEX-v3.2.4+0/SPEX.v3.2.4.x86_64-w64-mingw32.tar.gz"
