# Autogenerated wrapper script for SPEX_jll for i686-w64-mingw32
export libspexleftlu, libspexutil

using SuiteSparse_jll
using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("SPEX")
JLLWrappers.@declare_library_product(libspexleftlu, "libspexleftlu.dll")
JLLWrappers.@declare_library_product(libspexutil, "libspexutil.dll")
function __init__()
    JLLWrappers.@generate_init_header(SuiteSparse_jll, GMP_jll, MPFR_jll)
    JLLWrappers.@init_library_product(
        libspexleftlu,
        "bin\\libspexleftlu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspexutil,
        "bin\\libspexutil.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
