# Autogenerated wrapper script for SPEX_jll for x86_64-apple-darwin
export libspexleftlu, libspexutil

using SuiteSparse_jll
using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("SPEX")
JLLWrappers.@declare_library_product(libspexleftlu, "@rpath/libspexleftlu.1.dylib")
JLLWrappers.@declare_library_product(libspexutil, "@rpath/libspexutil.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(SuiteSparse_jll, GMP_jll, MPFR_jll)
    JLLWrappers.@init_library_product(
        libspexleftlu,
        "lib/libspexleftlu.1.0.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspexutil,
        "lib/libspexutil.1.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
